import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/marketing/legal-page";
import { site } from "@/lib/config";

const summary =
  "The rules for using the Nexus AI trial: trial limits, acceptable use, your content, third-party models and our responsibilities.";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: summary,
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      summary={summary}
      path="/terms"
      sections={[
        {
          id: "agreement",
          title: "Agreement",
          body: (
            <p>
              By using the {site.name} trial, you agree to these terms, the{" "}
              <Link href="/disclaimer">Disclaimer</Link> and our{" "}
              <Link href="/privacy">Privacy Policy</Link>. If you don&apos;t agree, please
              don&apos;t use the service.
            </p>
          ),
        },
        {
          id: "trial",
          title: "Trial Access and Limits",
          body: (
            <ul>
              <li>
                Nexus is a free trial. No account is needed, and you must be at least 13 years old
                to use it.
              </li>
              <li>
                Usage is limited per IP address each day and per chat. Limits reset at midnight UTC
                and may change at any time.
              </li>
              <li>
                Don&apos;t try to get around the limits, for example by rotating IP addresses or
                automating requests.
              </li>
              <li>
                Your chats are tied to your browser. If you clear its data, you may lose access to
                them, so export anything you want to keep.
              </li>
            </ul>
          ),
        },
        {
          id: "acceptable-use",
          title: "Acceptable Use",
          body: (
            <>
              <p>Don&apos;t use Nexus to:</p>
              <ul>
                <li>Break the law or infringe anyone&apos;s rights.</li>
                <li>
                  Create malware, plan violence, harass people or produce sexual content involving
                  minors.
                </li>
                <li>Upload content you don&apos;t have the right to use.</li>
                <li>Overload, probe or bypass the security or rate limits of the service.</li>
                <li>Break the usage policies of the model provider you&apos;re using.</li>
              </ul>
            </>
          ),
        },
        {
          id: "your-content",
          title: "Your Content",
          body: (
            <p>
              You own the messages and files you submit and the replies generated for you, to the
              extent the law allows. You give us permission to store and process that content only
              to provide the service to you.
            </p>
          ),
        },
        {
          id: "third-party-models",
          title: "Third-Party Models and API Keys",
          body: (
            <p>
              Replies are generated by third-party models. When you add your own API key, your use
              of that provider is governed by its terms, and it bills you directly. Prices shown in
              Nexus are for guidance only and may be out of date. Always check the provider&apos;s
              current pricing.
            </p>
          ),
        },
        {
          id: "availability",
          title: "Availability and Changes",
          body: (
            <p>
              We work to keep Nexus reliable but can&apos;t promise it will always be available or
              error-free. We may change or discontinue features, and we&apos;ll give reasonable
              notice for significant changes when we can.
            </p>
          ),
        },
        {
          id: "termination",
          title: "Ending Your Use",
          body: (
            <p>
              You can delete all of your trial data at any time from Settings. We may block IP
              addresses or trial IDs that break these terms or put the service or other users at
              risk, and we may end the trial at any time.
            </p>
          ),
        },
        {
          id: "liability",
          title: "Disclaimers and Liability",
          body: (
            <p>
              Nexus is provided &ldquo;as is&rdquo;. AI output can be inaccurate. See the{" "}
              <Link href="/disclaimer">Disclaimer</Link>. To the fullest extent the law allows, we
              aren&apos;t liable for indirect or consequential losses arising from your use of the
              service.
            </p>
          ),
        },
        {
          id: "contact",
          title: "Contact",
          body: (
            <p>
              Questions about these terms? Email{" "}
              <a href={`mailto:${site.contactEmail}`}>{site.contactEmail}</a>.
            </p>
          ),
        },
      ]}
    />
  );
}
