import type { Catalog, Usage } from "@/lib/types";

export const STATIC_CATALOG: Catalog = {
  checked: "2026-09-25",
  groups: [
    {
      id: "fast",
      name: "Fast",
      description: "Answers in a second or two. Best for everyday questions.",
    },
    {
      id: "thorough",
      name: "Slow & Thorough",
      description: "Thinks step by step before answering. Slower, but more careful.",
    },
    {
      id: "new",
      name: "New",
      description: "The latest model on Groq, in preview, at three thinking levels.",
    },
  ],
  groq: [
    {
      id: "openai/gpt-oss-20b",
      name: "GPT-OSS 20B",
      developer: "OpenAI",
      group: "fast",
      reasoning_effort: "low",
      context: 131072,
      speed: "About 1,000 words per second",
      best_for: "Quick everyday questions, short emails, summaries and simple explanations.",
      why: "Pick this when you want an answer right now and the question isn't complicated.",
      default: true,
    },
    {
      id: "openai/gpt-oss-120b",
      name: "GPT-OSS 120B",
      developer: "OpenAI",
      group: "fast",
      reasoning_effort: "medium",
      context: 131072,
      speed: "About 500 words per second",
      best_for:
        "Smarter all-round answers: writing, coding help and research that still arrive almost instantly.",
      why: "Pick this when the fastest model feels too shallow but you don't want to wait.",
    },
    {
      id: "openai/gpt-oss-20b:thorough",
      name: "GPT-OSS 20B Thorough",
      developer: "OpenAI",
      group: "thorough",
      reasoning_effort: "high",
      context: 131072,
      speed: "A few seconds of thinking, then a fast answer",
      best_for:
        "Homework-style maths, step-by-step logic and checking your work, with a shorter wait.",
      why: "The same model as GPT-OSS 20B, told to think harder. A lighter, quicker option than 120B Thorough.",
    },
    {
      id: "openai/gpt-oss-120b:thorough",
      name: "GPT-OSS 120B Thorough",
      developer: "OpenAI",
      group: "thorough",
      reasoning_effort: "high",
      context: 131072,
      speed: "Takes longer because it reasons step by step first",
      best_for:
        "Maths, logic puzzles, tricky code, planning and anything where accuracy matters more than speed.",
      why: "Pick this when a wrong answer would cost you more than a few extra seconds of waiting.",
    },
    {
      id: "qwen/qwen3.8-27b:instant",
      name: "Qwen 3.8 27B Instant",
      developer: "Alibaba",
      group: "new",
      reasoning_effort: "none",
      context: 131072,
      speed: "Answers straight away with no thinking step",
      best_for: "Fast replies in many languages, rewriting and translating text.",
      why: "The newest model with its thinking switched off. Pick it for speed, especially outside English.",
      preview: true,
    },
    {
      id: "qwen/qwen3.8-27b",
      name: "Qwen 3.8 27B",
      developer: "Alibaba",
      group: "new",
      reasoning_effort: "default",
      context: 131072,
      speed: "Moderate",
      best_for:
        "The newest model on Groq: careful problem solving, coding and multilingual answers.",
      why: "Pick this to try the latest model. It's a preview, so Groq may change or retire it at short notice.",
      preview: true,
    },
    {
      id: "qwen/qwen3.8-27b:thorough",
      name: "Qwen 3.8 27B Thorough",
      developer: "Alibaba",
      group: "new",
      reasoning_effort: "high",
      context: 131072,
      speed: "Slower, thinks deeply before answering",
      best_for: "Hard coding problems and multi-step reasoning with the newest model.",
      why: "The newest model at maximum effort. Pick it when you want a second opinion from a different model family.",
      preview: true,
    },
  ],
  think: {
    engine: "GPT-OSS 120B Thorough + JEV by TypeSafe",
    jev_enabled: true,
  },
  providers: [
    {
      id: "openai",
      name: "OpenAI",
      tagline: "GPT models for writing, coding and everyday reasoning.",
      key_url: "https://platform.openai.com/api-keys",
      key_placeholder: "sk-...",
    },
    {
      id: "anthropic",
      name: "Anthropic Claude",
      tagline: "Claude models known for careful writing, analysis and long documents.",
      key_url: "https://console.anthropic.com/settings/keys",
      key_placeholder: "sk-ant-...",
    },
    {
      id: "gemini",
      name: "Google Gemini",
      tagline: "Gemini models with very long context and strong multimodal skills.",
      key_url: "https://aistudio.google.com/app/apikey",
      key_placeholder: "AIza...",
    },
    {
      id: "openrouter",
      name: "OpenRouter",
      tagline: "One key for hundreds of models from every major lab, with live pricing.",
      key_url: "https://openrouter.ai/settings/keys",
      key_placeholder: "sk-or-...",
    },
    {
      id: "xai",
      name: "xAI Grok",
      tagline: "Grok models with real-time knowledge and a direct style.",
      key_url: "https://console.x.ai",
      key_placeholder: "xai-...",
    },
    {
      id: "deepseek",
      name: "DeepSeek",
      tagline: "Low-cost models that are strong at maths and code.",
      key_url: "https://platform.deepseek.com/api_keys",
      key_placeholder: "sk-...",
    },
    {
      id: "mistral",
      name: "Mistral AI",
      tagline: "European models that are fast, efficient and multilingual.",
      key_url: "https://console.mistral.ai/api-keys",
      key_placeholder: "...",
    },
  ],
};

export const STATIC_USAGE: Usage = {
  messages_limit: 25,
  messages_used: 0,
  messages_left: 25,
  uploads_limit: 5,
  uploads_used: 0,
  uploads_left: 5,
  voice_limit: 30,
  voice_used: 0,
  voice_left: 30,
  max_turns_per_chat: 15,
  resets_at: "",
  live: false,
};
