import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";
import { site } from "@/lib/config";

const summary =
  "What Nexus AI can and can't do, and why you should check important answers before acting on them.";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: summary,
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      summary={summary}
      path="/disclaimer"
      sections={[
        {
          id: "ai-output",
          title: "AI Can Be Wrong",
          body: (
            <p>
              Replies from {site.name} are generated by AI models. They can be inaccurate,
              incomplete, out of date or biased, even when they sound confident and even when they
              include sources. Check important information against reliable sources.
            </p>
          ),
        },
        {
          id: "not-professional-advice",
          title: "Not Professional Advice",
          body: (
            <p>
              Nexus doesn&apos;t provide medical, legal, financial, tax or other professional
              advice. Don&apos;t use it as a substitute for a qualified professional, and never
              delay seeking professional help because of something Nexus said.
            </p>
          ),
        },
        {
          id: "think-mode",
          title: "Think Mode Recommendations",
          body: (
            <p>
              Think mode helps structure a decision by listing options, trade-offs and a
              recommendation with a confidence level. It&apos;s a thinking aid, not a guarantee. You
              remain responsible for the decisions you make.
            </p>
          ),
        },
        {
          id: "sources",
          title: "Web Results and Documents",
          body: (
            <p>
              When Nexus searches the web or your documents, it depends on the quality of those
              sources. Linked websites are run by third parties, and we aren&apos;t responsible for
              their content.
            </p>
          ),
        },
        {
          id: "costs",
          title: "Third-Party Costs",
          body: (
            <p>
              If you use your own API key, the provider charges you for usage. Prices shown in Nexus
              are estimates. Check your provider&apos;s dashboard for actual costs, and set spending
              limits there.
            </p>
          ),
        },
        {
          id: "contact",
          title: "Contact",
          body: (
            <p>
              Spotted a harmful or wrong answer? Tell us at{" "}
              <a href={`mailto:${site.contactEmail}`}>{site.contactEmail}</a>.
            </p>
          ),
        },
      ]}
    />
  );
}
